Feature/auth screens
Burak-Tasci/wake-your-friends-up pull request #6
Opened 2023-03-29 11:27 UTC by evirgenoguz

2023-03-29 16:02 UTC, Burak-Tasci requested changes

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/ui/dialog/ResetPasswordDialog.kt
> +fun Fragment.setupBottomSheetDialog(
dosyanın ismi ResetPassworfDialog ama buraya bir fragment extension'ı yazılmış. Yazılan extension ise her fragment'ı kapsamayan view'lere erişim istiyor. Ya bunu gerekli Fragment dosyasının içine yazalım ya da kaldıralım.

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/di/NetworkModule.kt
> +    @Singleton
Bunu repository module içine alalım

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/ext/FragmentExt.kt
> +            Toast.LENGTH_LONG
yorum satırını kaldıralım

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/data/model/request/UserRequestModel.kt
> +    val fullName: String,
fullName komple kalksın, çünkü istek sırasında kullanmıyoruz ve bu bir request model yani istek modeli

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/data/model/response/UserResponseModel.kt
> +    val fullName: String = "",
yine fullname kalkabilir

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/ui/features/login/LoginFragment.kt
> +                findNavController().navigate(R.id.action_loginFragment_to_registerFragment)
action id yerine generate edilmiş directions sınıfı üzerinden action'a erişelim. Daha okunaklı olur.

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/ui/features/onboarding/OnBoardingFragment.kt
> +            findNavController().navigate(R.id.action_onBoardingFragment_to_startFragment)
Aynı şekilde generate edilmiş Directions sınıfı kullanılabilir

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/ui/features/register/RegisterFragment.kt
> +                findNavController().navigate(R.id.action_registerFragment_to_loginFragment)
Aynı şekilde generate edilmiş Directions sınıfı kullanılabilir

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/ui/features/register/RegisterFragment.kt
> +                            "${it.body.fullName} successfully auth",
fullName'i kaldırdığımızda buraya todo bırakabilirsin, bir sonraki task'ı yapacak kişi değişikliği yapar

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/ui/features/register/RegisterViewModel.kt
> +                    _register.postValue(NetworkResult.Success(UserResponseModel(fullName = userRequestModel.fullName, email = userRequestModel.email)))
Burada post ettiğimiz veriyi repo'dan yani addOnSuccess içinden almamız gerekiyor, zaten yolladığımız veriyi livedata'ya vermemize gerek yok, oradan gelen uid'i response model içine koyabiliriz.

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/ui/features/start/StartFragment.kt
> +                findNavController().navigate(R.id.action_startFragment_to_loginFragment)
Aynı şekilde generate edilmiş Directions sınıfı kullanılabilir

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/ui/features/start/StartFragment.kt
> +                findNavController().navigate(R.id.action_startFragment_to_registerFragment)
Aynı şekilde generate edilmiş Directions sınıfı kullanılabilir

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/ui/features/start/StartViewModel.kt
> +    // TODO: Implement the ViewModel
BaseViewModel'dan kalıtım alsın

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/ui/features/start/StartViewModel.kt
> +    // TODO: Implement the ViewModel
suanda kullanılıp kullanılmaması çok önemli değil, yapı hazır olsun ileride kullanılabilir

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/drawable/button_background.xml
> +    android:width="105dp"
bg_[BUTONUN_İŞİ_YADA_ÖZELLİĞİ] şeklinde bir format olması gerekiyor. Bu şekilde dosya ismine baktığımda bunun ne yaptığı anlaşılmıyor

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/dialog_reset_password.xml
> +        android:layout_marginTop="10dp"
bu dpleri dimens.xml üzerinden vermeliyiz. Mümkün olduğunca 4'ün katları şeklinde olsun

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/dialog_reset_password.xml
> +        android:textSize="18sp"
aynı şekilde textsize için de dimens kullanılmalı

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/dialog_reset_password.xml
> +        android:layout_marginTop="10dp"
margin_12dp

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/dialog_reset_password.xml
> +        android:textSize="18sp"
textsize_18sp

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/dialog_reset_password.xml
> +            android:layout_marginEnd="5dp"
bu layout'larda margin'leri dirense taşırsın hepsine yazmıyorum

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_login.xml
> +        app:layout_constraintStart_toStartOf="parent"
match_parent verdiğin zaman start ve end constraint'leri ezmiş oluyorsun zaten, bu yüzden onları vermene gerek yok

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_login.xml
> +                app:layout_constraintEnd_toEndOf="parent"
Aynı şekilde yukarıdaki gibi

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_login.xml
> +                app:layout_constraintEnd_toEndOf="parent"
start end constraint'lerine gerek yok

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_login.xml
> +                android:clickable="true"
TextView zaten clickable ve focusable

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_register.xml
> +        app:layout_constraintStart_toStartOf="parent"
start end kaldırabiliriz

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_register.xml
> +                android:layout_marginTop="32dp"
burası kalkacak

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_register.xml
> +                android:layout_marginTop="16dp"
buna inputType email verelim ki kullanıcının klavyesi email girişine uygun olsun. Aynı zamanda suanda kullanıcı burada enter'a basarak aşağı inebiliyor, onu da önlemek için bunu single line yapman gerekiyor

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_register.xml
> +                app:layout_constraintStart_toStartOf="parent"
start end'e gerek yok

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_register.xml
> +                android:hint="@string/password"
password için inputType password verelim

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_register.xml
> +                app:layout_constraintEnd_toEndOf="parent"
start ve end gerek yok

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_register.xml
> +                    android:clickable="true"
clickable ve focusable gerek yok

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_start.xml
> +        tools:layout_editor_absoluteX="0dp" />
bu neden var

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/layout/fragment_start.xml
> +        android:src="@drawable/ic_alarm_clock"
imageView'ın width height'ini bu şekilde statik vermek küçük telefonlarda problem yaratır, constraintDimensionRatio adında bir attribute var onu araştır

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/res/values/strings.xml
> +    <string name="sign_in_dont_have_an_account">Don\'t have an account?</string>
sign_in yerine login yapalım bunun prefix'ini

2023-03-29 16:02 UTC, Burak-Tasci commented on app/src/main/java/com/jungle/wake_your_friends_up/data/repository/AuthRepository.kt
> +    private val firebaseAuth: FirebaseAuth,
@Inject'i kaldıralım buradan, inject ediliş biçimini ViewModelModule.kt içinde belirticez. Yoksa her yerden inject edilebilir olur

2023-03-30 11:17 UTC, evirgenoguz commented on app/src/main/java/com/jungle/wake_your_friends_up/ui/dialog/ResetPasswordDialog.kt
> +fun Fragment.setupBottomSheetDialog(
FragmentExt in icine aldim.

2023-03-31 10:52 UTC, evirgenoguz commented on app/src/main/java/com/jungle/wake_your_friends_up/ui/features/register/RegisterViewModel.kt
> +                    _register.postValue(NetworkResult.Success(UserResponseModel(fullName = userRequestModel.fullName, email = userRequestModel.email)))
Abi ben anlamadim

2023-04-01 19:35 UTC, Burak-Tasci approved these changes

2023-04-01 19:35 UTC, merged